version: '3'
services:

  mysql:
    image: mysql
    ports:
      - '3306:3306'
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=sequelize
      - MYSQL_ROOT_PASSWORD=123456
    command: --default-authentication-plugin=mysql_native_password

  app:
    image: node:13-alpine
    ports:
      - '80:3000'
    volumes:
      - ./:/node-app
    depends_on:
      - mysql
    networks:
      - app-network
    working_dir: /node-app
    command: node index.js

networks: 
  app-network:
    driver: bridge